Add -fminimize-whitespace preprocessor flag when Clang >= 14 to increase cache hits
mozilla/sccache pull request #1055
Opened 2021-10-16 20:40 UTC by InnovativeInventor

This proof of concept tries to take advantage of the new `-fminimize-whitespace` preprocessor option in Clang (14.0.0, not released yet). `-fminimize-whitespace` was added to Clang with the intention to help increase the chance of a cache hit in tools like `sccache` when only whitespace changes.

To illustrate this change, here are two sample C programs that previously wouldn't trigger a cache hit before this PR, but now do (when using Clang >= 14):
```c
#include <stdio.h>

int main() 

{

   printf("Hello World!");
return 0;
}
```
```c
#include <stdio.h>

int main() {printf("Hello World!");return 0;}
```

I also added some code to expose the compiler version to the preprocessor. This could be useful if version-dependent features are added to `sccache` in the future.

Feedback on this is definitely welcome! Note that Clang 14.0.0 is still in progress, so there is no rush to merge in this PR.

2021-10-17 00:37 UTC, Meinersbur commented
Great addition! `-fminimize-whitespace` should allow reusing the cached artifact even after running clang-format over the source (at least without ` --sort-includes`).

2021-11-03 21:27 UTC, sylvestre commented
Could you please fix the conflict?
Also, would it be possible to add a test?

2021-11-13 18:01 UTC, drahnr commented
Does this change the resulting binary behavior? Will `__LINE__` and debug info point to the correct locations in the source code?

2021-11-14 05:41 UTC, Meinersbur commented
> Does this change the resulting binary behavior? Will `__LINE__` and debug info point to the correct locations in the source code?

`__LINE__` directives are already replaced in the preprocessor output. With just `-E`, line directives and newlines remain the same. With `-E -P`, no line directives are emitted anyway so there are no line numbers to preserve anyway. This patch only adds `-fminimize-whitespace` when `-P` is added, although there would be no problem to add it as well when just using `-E`.

2021-11-14 21:47 UTC, InnovativeInventor commented
> Could you please fix the conflict? 

Just did. I also addressed the style issues that clippy was warning about.

> Also, would it be possible to add a test?

I'm not quite sure how I should do this (since clang 14 isn't released yet, I was thinking about pinning a particular commit and building it in the CI environment). Do you have any suggestions?

2021-11-15 12:34 UTC, sylvestre commented
@InnovativeInventor maybe create a job CI task and use a clang-14 package from apt.llvm.org for Ubuntu  ?

2021-11-15 12:34 UTC, sylvestre commented
It seems that it need a clear rebase:
"This branch cannot be rebased due to conflicts"

2021-11-17 18:45 UTC, InnovativeInventor commented
> @InnovativeInventor maybe create a job CI task and use a clang-14 package from apt.llvm.org for Ubuntu ?

Ok, just pushed some tests (only for Ubuntu right now) that check that whitespace causes a cache miss on clang-13 (as expected) and a cache hit on clang-14. I included a check for clang-13 mostly to demonstrate that the tests would fail if the feature was not implemented properly (to show that the tests actually work).

I also cleaned up the commit history, so it should be ready now (CI appears to pass on my fork: https://github.com/InnovativeInventor/sccache/actions/runs/1473112165).

2021-12-20 18:16 UTC, sylvestre commented
Would it be possible to not hardcode the llvm version ?
or it is too much work?

2021-12-20 21:18 UTC, glandium commented
You can't rely on version number for clang, because Xcode's clang has a version that corresponds to the Xcode version, and that doesn't match the LLVM version.

2022-01-20 20:50 UTC, Meinersbur commented
What would be the alternative to use the llvm version? One could call the compiler at the beginning with the `-fminimize-whitespace` to see whether it it is accepted, but it would mean another compiler invocation every time. Would that be acceptable?

2022-02-17 17:10 UTC, mitchhentges requested changes
Hey, this patch is really cool, good idea on using `-fminimize-whitespace`.

Unfortunately, as alluded by glandium, we can't lean on the version number because XCode's version isn't aligned with LLVM's - see [this table](https://en.wikipedia.org/wiki/Xcode#Xcode_11.x_-_13.x_(since_SwiftUI_framework)_2).

> What would be the alternative to use the llvm version? One could call the compiler at the beginning with the -fminimize-whitespace to see whether it it is accepted, but it would mean another compiler invocation every time. Would that be acceptable?

I think the right move would be to call `clang` once to query if it supports `-fminimize-whitespace`, caching the result in the `sccache` server (probably), then reusing that value for future usages of the same `clang`.

It does cost a compiler call to determine support, but IIRC we already incur a "call the compiler" cost to determine its version. We can call again (or, ideally, append to that existing "detect_c_compiler" call) to get other feature information.

2022-02-17 18:07 UTC, Meinersbur commented
Wouldn't it be sufficient to identify Apply clang with `__apple_build_version__ ` or `__APPLE_CC__`? [This is how CMake detects ApplyClang](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/Compiler/AppleClang-DetermineCompiler.cmake#L2).

2022-02-17 18:37 UTC, InnovativeInventor commented
@Meinersbur is there a `__clang_minimize_whitespace__` thing I can check for? If not, I can call `--help` and parse the flags (might be more brittle, though).

2022-02-17 18:52 UTC, mitchhentges commented
> Wouldn't it be sufficient to identify Apply clang with __apple_build_version__ or __APPLE_CC__? [This is how CMake detects AppleClang](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/Compiler/AppleClang-DetermineCompiler.cmake#L2).

Hmm, that could work, yeah.
We'll probably want to store both pieces of information (version + apple/llvm clang) on the sccache compiler object - or, front-load the decision-making, and just store "supports minimize whitespace" instead.
Related: can we remove `version` (or whatever we store) from the top level `CCompiler` struct, and just store the values needed for minimize-whitespace decision-making on the `Clang` struct instead?

2022-02-17 19:37 UTC, Meinersbur commented
> @Meinersbur is there a `__clang_minimize_whitespace__` thing I can check for? If not, I can call `--help` and parse the flags (might be more brittle, though).

There is not. Usually preprocessor macros are about language features, not which command line flags are accepted. Before [feature test macros](https://en.cppreference.com/w/cpp/feature_test), compiler version was the go-to mechanisms for language features. I could try to add it though, but clang-14 has already branched and I am not sure it would be included before release.

Before parsing `--help`, just invoke it with `-fminimize-whitespace` and see whether you get an error.

2022-04-05 18:16 UTC, Meinersbur commented
With clang 14 now released, any update on this PR?

2022-04-29 06:32 UTC, Meinersbur commented
This PR is superseded by #1162 and can be closed. Thanks @drahnr for merging!

2022-04-29 06:34 UTC, closed without merging

2022-04-29 20:09 UTC, InnovativeInventor commented
> This PR is superseded by #1162 and can be closed. Thanks @drahnr for merging!

Nice!