Allow building individual storage features without 'azure'
mozilla/sccache pull request #1255
Opened 2022-08-03 13:35 UTC by sad-sage

All storage features import and use `chrono` from the `util` module.
Alas, the definition of `chrono` is declared behind the *azure* feature
flag which makes building any individual storage feature without *azure*
enabled impossible.

Since the `chrono` definition is used in multiple modules it should not
be hidden behind any feature flags.

2022-08-03 15:59 UTC, sad-sage commented
I'm fairly new to Rust (and GitHub). Is there some documentation or a place where I can find the definition of the failed check so that I can reproduce it locally. I'd like to avoid spamming this PR with trial-and-error fixes if I can.

2022-08-03 17:55 UTC, drahnr commented
> I'm fairly new to Rust (and GitHub). Is there some documentation or a place where I can find the definition of the failed check so that I can reproduce it locally. I'd like to avoid spamming this PR with trial-and-error fixes if I can.

If you click on "details" it brings you to the GitHub actions log, where the failing step is highlighted with a red circle with a black x

2022-08-04 08:43 UTC, sad-sage commented
Fix PR checks: disabled the `chrono` declaration for `dist-server` which doesn't use/need it.

2022-08-04 08:47 UTC, drahnr requested changes
<pre><font color="#444444"> 120</font>   <font color="#444444">│</font> <font color="#FFFFFF">[</font><font color="#AFD75F">features</font><font color="#FFFFFF">]</font>
<font color="#444444"> 121</font>   <font color="#444444">│</font> <font color="#FF5F5F">default</font><font color="#FFFFFF"> = [</font><font color="#D7D787">&quot;all&quot;</font><font color="#FFFFFF">]</font>
<font color="#444444"> 122</font>   <font color="#444444">│</font> <font color="#FF5F5F">all</font><font color="#FFFFFF"> = [</font><font color="#D7D787">&quot;dist-client&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;redis&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;s3&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;memcached&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;gcs&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;azure&quot;</font><font color="#FFFFFF">]</font>
<font color="#444444"> 123</font>   <font color="#444444">│</font> <font color="#FF5F5F">azure</font><font color="#FFFFFF"> = [</font><font color="#D7D787">&quot;</font><span style="background-color:#D7D787"><font color="#1E1E1E">chrono</font></span><font color="#D7D787">&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;hyper&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;hyperx&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;reqwest&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;url&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;hmac&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;md-5&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;sha2&quot;</font><font color="#FFFFFF">]</font>
<font color="#444444"> 124</font>   <font color="#444444">│</font> <font color="#FF5F5F">s3</font><font color="#FFFFFF"> = [</font><font color="#D7D787">&quot;</font><span style="background-color:#D7D787"><font color="#1E1E1E">chrono</font></span><font color="#D7D787">&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;hyper&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;hyperx&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;reqwest&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;simple-s3&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;hmac&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;sha-1&quot;</font><font color="#FFFFFF">]</font>
<font color="#444444"> 125</font>   <font color="#444444">│</font> <font color="#FF5F5F">simple-s3</font><font color="#FFFFFF"> = []</font>
<font color="#444444"> 126</font>   <font color="#444444">│</font> <font color="#FF5F5F">gcs</font><font color="#FFFFFF"> = [</font><font color="#D7D787">&quot;</font><span style="background-color:#D7D787"><font color="#1E1E1E">chrono</font></span><font color="#D7D787">&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;hyper&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;hyperx&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;percent-encoding&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;reqwest&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;ring&quot;</font><font color="#FFFFFF">, </font><font color="#D7D787">&quot;url&quot;</font><font color="#FFFFFF">]</font>
<font color="#444444"> 127</font>   <font color="#444444">│</font> <font color="#FF5F5F">memcached</font><font color="#FFFFFF"> = [</font><font color="#D7D787">&quot;memcached-rs&quot;</font><font color="#FFFFFF">]</font>
<font color="#444444"> 128</font>   <font color="#444444">│</font> <font color="#FF5F5F">native-zlib</font><font color="#FFFFFF"> = []</font>
</pre>

`chrono` is an optional dependency that is pulled in by a bunch of features. as such, the above is insufficient to cover all possible feature flags.

So one has to use `#[cfg(any(feature = "A', feature = "B", ..))]` covering all relevant features. The CI does not enforce that kind of matrix build, so please be very diligent. Note that the alternative is to make `chrono` a non-optional dependency, but that would make clippy angry due to - in some cases - unused crate deps.

2022-08-04 09:55 UTC, sad-sage commented
Thank you for the very informative explanation. Pushed another fix attempt hiding the `chrono` definition behind all relevant features that I could find, based on:
```
$ grep "\"chrono\"" -r Cargo.toml 
azure = ["chrono", "hyper", "hyperx", "reqwest", "url", "hmac", "md-5", "sha2"]
s3 = ["chrono", "hyper", "hyperx", "reqwest", "simple-s3", "hmac", "sha-1"]
gcs = ["chrono", "hyper", "hyperx", "percent-encoding", "reqwest", "ring", "url"]

```

2022-08-05 08:40 UTC, sad-sage commented
Push `cargo fmt` fix.

2022-08-05 09:34 UTC, drahnr approved these changes

2022-08-05 09:35 UTC, merged