Remove the dependency on the local-encoding crate
mozilla/sccache pull request #1376
Opened 2022-10-30 22:33 UTC by gabrielesvelto

The local-encoding crate was used to convert Windows paths using the user machine's OEM codepoint. This functionality is very small and was easily folded in the code that requires it.

Removing this crate cuts 11 crates from sccache dependencies including many very old and unmaintained ones.

2022-10-31 06:41 UTC, drahnr requested changes
Thank you for cutting that legacy crate out of our dependency tree! Very much in need of test cases though, covering both valid and invalid input.

2022-10-31 07:01 UTC, sylvestre commented
nice to see you here @gabrielesvelto :)
and clippy isn't super happy!

2022-11-02 09:09 UTC, gabrielesvelto commented
> nice to see you here @gabrielesvelto :) and clippy isn't super happy!

I've got some scalability improvements in the pipe but first I need to clean up some dependencies 😸. clippy 1.60 doesn't complain on my machine (in fact I added that code using `MaybeUninit<>` because it was complaining). I suppose I could rewrite that code to make both happy.

2022-11-02 09:35 UTC, gabrielesvelto commented
It seems like I could appease clippy (and get rid of the `MaybeUninit<>`s). This PR also paves the way to be able to build and run sccache on Windows/AArch64 which is currently broken unless ones disables all optional features. More changes are required but this is half of it.

2022-11-04 17:59 UTC, gabrielesvelto commented
Review ping

2022-11-08 17:23 UTC, sylvestre commented
good coverage: https://app.codecov.io/gh/mozilla/sccache/pull/1376
![image](https://user-images.githubusercontent.com/733326/200632991-722379fe-23a3-49d9-b208-dd6a63837190.png)

2022-11-08 17:23 UTC, merged

2022-11-09 12:40 UTC, emabrey commented
:+1: