Determine support for -fminimize-whitespace via test execution.
mozilla/sccache pull request #1555
Opened 2023-01-11 23:18 UTC by Meinersbur

Commit da2934f/PR #1162 added the -fminimize-whitespace flag when proprocessing and derived compiler support from the compiler version (clang >= 14). It unfortunately had a bug in the detection mechanism and also the unittest such that the flag was never used:

 1. Clang expands the __VERSION__ macro to a string (e.g. "LLVM Clang 14.0.0"). The additional quotes caused the version check to fail. Originally, the --version output was passed to the version check function which does not contain such quotes.

 2. The regression test checked for whether the compiler is "clang", but not "clang++".

 3. Wrong regex group names used for checking for Apple caused the check to always expect a cache miss.

This patch changes the check whether -fnormalize-whitespace is supported to a test invocation with that flag. Only the regression test continues to be based on the know versions that support the flag to be independent on the feature test. When Apple clang one day adds support for the flag, the test will need to be updated.

2023-01-14 08:06 UTC, sylvestre commented on src/compiler/compiler.rs
> +                // Check whether the compiler also supports the -E -fminimize-whitespace flag
Please move this into a separate function and add a test to verify it won't regress

2023-01-14 08:06 UTC, sylvestre commented on src/compiler/compiler.rs
> +            Some("__VERSION__") => None,
Please mive this into a function too with some tests. Thanks

2023-02-12 07:58 UTC, sylvestre commented
@Meinersbur ping ?

2023-02-14 09:04 UTC, sylvestre requested changes
see above

2023-02-26 07:11 UTC, Meinersbur commented
Sorry for the waiting, I was exploring test strategies and I am not very familiar with Rust.

I poked some abstraction holes to be able to check the `has_fminimize_whitespace` flag in `test_detect_compiler_kind_clang` (`as_any()`, `pub compiler`), but checking the result of `detect_fminimize_whitespace_support` in two separate tests. Which approach do you prefer?

2023-03-15 22:34 UTC, Meinersbur commented
I removed the test that requires a downcasting `detect_compiler` and kept the one that just calls `detect_fminimize_whitespace_support` . I would be happy for another review.

2023-04-19 20:15 UTC, Meinersbur commented
As far as I understand, the test failures are unrelated. 

 * `test freebsd-13.1 rust stable` also fails on main
 * The integration test seem to fail sporadically due to misses using a remote URL cache, e.g. https://github.com/mozilla/sccache/actions/runs/4722730937/jobs/8377898781

2023-05-10 15:02 UTC, Xuanwo commented
> * The integration test seem to fail sporadically due to misses using a remote URL cache, e.g. https://github.com/mozilla/sccache/actions/runs/4722730937/jobs/8377898781

I think we should not depend on ghac while running tests like `clang`. For tests, we should use local fs instead. We can remove https://github.com/mozilla/sccache/actions/runs/4938282959/workflow?pr=1555#L412 directly.

2024-02-20 12:35 UTC, sylvestre commented
needs rebasing, please reopen when ready.

2024-02-20 12:35 UTC, closed without merging