fixed --no-default-features --features=gcs warnings
mozilla/sccache pull request #2287
Opened 2024-11-12 06:21 UTC by Aditya-PS-05

closes #2056 

## Summary
Removed the warnings by adding `#[allow(dead_code)]` attribute.

2024-11-12 08:37 UTC, sylvestre commented
@Aditya-PS-05 why not fixing it for real ?

2024-11-12 08:54 UTC, Aditya-PS-05 commented
Ok

2024-11-12 13:51 UTC, sylvestre requested changes
as said above

2025-01-02 17:58 UTC, sylvestre commented
please reopen when ready

2025-01-02 17:58 UTC, closed without merging