Add the ability to clear a cache.
mozilla/sccache pull request #858
Opened 2020-09-28 06:59 UTC by rthomas

This adds the --clear-cache argument that will remove the contents of
the cache.

This is implemented as `clear()` on the `Storage` trait - however it
is only implemented for the `DiskCache` (and `LruDiskCache`)
implementations. Any invocation on the other implementations will
return an `Err`.

A test for the `LruDiskCache` has also been included in this commit.

2020-10-15 22:22 UTC, rthomas commented
Friendly ping on this.

2020-12-03 17:07 UTC, drahnr commented
@rthomas would you mind re-creating this against paritytech/sccache ?

2020-12-03 21:05 UTC, rthomas commented
Sure thing I'll try to get to it this weekend - has this repo been abandoned?

2020-12-04 01:49 UTC, rthomas commented
Created as https://github.com/paritytech/sccache/pull/27

2020-12-10 01:53 UTC, glandium requested changes

2020-12-10 01:53 UTC, glandium commented on src/cache/azure.rs
> +        f_err(anyhow!("AzureBlobCache::clear is not implemented"))
Can you change the error messages to something like "Cannot clear the cache on Azure storage"?

2020-12-10 01:53 UTC, glandium commented on lru-disk-cache/src/lib.rs
> +            if entry.path().is_dir() {
It would be better to use file_type() rather than path().

2020-12-10 01:53 UTC, glandium commented on lru-disk-cache/src/lib.rs
> +        let p3 = f.create_file("file3", 10);
Maybe create a subdirectory too?

2021-03-06 15:05 UTC, petr-tik commented
A happy user of sccache checking in to see if this PR and fork are still active. Thanks for implementing @rthomas, are you still interested in getting this merged in this repo? 

If not, would you be ok, if I addressed the code review by @glandium and finalised this?

2021-11-14 11:30 UTC, sylvestre commented
it will need to be rebased too

2022-02-12 15:12 UTC, closed without merging

2022-02-14 15:37 UTC, mitchhentges commented
(It looks like this PR got closed due to the renaming of `master` => `main`.)
@petr-tik if you're still interested in tackling this work, that'd be much appreciated :)