Still read config file from Library/Preferences if it exists
mozilla/sccache pull request #921
Opened 2021-01-06 01:15 UTC by glandium

Fixes #919

2021-01-06 01:16 UTC, glandium commented
@mstange Can you double check that this uses a config from ~/Library/Preferences if you move it back there?

2021-01-06 04:33 UTC, mstange commented
I will check tomorrow.

Looking at the patch, I think that if both files are present, the patch prefers the one in Preferences. I think it would be better to prefer the one in the new location.

2021-01-06 13:51 UTC, mitchhentges approved these changes
Looks good, but I agree with :mstange's suggestion on prioritizing our new config path first.

2021-01-06 17:26 UTC, mstange commented
> @mstange Can you double check that this uses a config from ~/Library/Preferences if you move it back there?

Confirmed, the patch works.

```
% mv ~/Library/Application\ Support/Mozilla.sccache/config ~/Library/Preferences/Mozilla.sccache/
% SCCACHE_LOG=trace ./target/release/sccache --dist-status
[...]
[2021-01-06T17:23:37Z DEBUG sccache::config] Attempting to read config file at "/Users/mstange/Library/Preferences/Mozilla.sccache/config"
[...]
{"SchedulerStatus":["http://192.168.2.146:10600/",{"num_servers":1,"num_cpus":16,"in_progress":0}]}%
```

2021-01-06 21:08 UTC, cgsheeh requested changes

2021-01-06 21:08 UTC, cgsheeh commented on src/config.rs
> +}
Maybe we fast-path the new path if it already exists, if not we check the old path and return that if it exists, and return the new path if neither exist yet.

Another option is to migrate the config file and/or log a warning somewhere saying we're moving the config file and we're deprecating use of the old one.

2021-01-06 21:08 UTC, cgsheeh commented on src/config.rs
> +fn config_file(env_var: &str, leaf: &str) -> PathBuf {
Regardless of what we do, we should have a comment describing why we need to do this config-file-search dance.

2021-01-07 15:18 UTC, cgsheeh approved these changes

2021-01-07 21:00 UTC, merged