Cache file hashes
mozilla/sccache pull request #953
Opened 2021-02-11 13:45 UTC by michaelwoerister

This PR adds a cache for file hashes in the server, as suggested in https://github.com/mozilla/sccache/issues/758. 

The implementation is kind of simplistic (maybe even too much so):

- It does not try to avoid races between multiple threads hashing the same file. If one thread is already hashing file `x` and another thread wants to do the same, it will just go ahead an calculate the hash by itself. Both threads will write the hash to the cache (in the order they finish). This should be a benign race since hashes are always associated with their timestamps. In the worst case, a long-running hash computation overwrites a new entry with an outdated hash. In that case the next request for the file hash would re-do the hashing again.

- The cache is simply kept in a local static variable. Keeping it somewhere else requires lots of additional parameter passing in many places. I'm undecided on whether I think this ugly or an example of good encapsulation `:)`

In my local testing this kind of caching did not make a lot of difference for C/C++ builds. Those seem to be completely dominated by the C preprocessor. It did not get a chance to benchmark this with Rust code yet.

Feedback welcome!

Closes https://github.com/mozilla/sccache/issues/758.

cc @froydnj @luser

2021-03-10 08:23 UTC, glandium requested changes
I haven't looked deeply in the details yet. Intuitively, I'd guess the reduction in how much hashing happens compensates for the extra syscalls to get the file metadata, even on Windows where I/O tends to be awful, but I'd like to benchmark this somehow before considering for a merge. I'm also not sure whether I'd queue that for 0.2 or 0.3...

2021-03-10 08:23 UTC, glandium commented on src/util.rs
> +    hashes: Arc<Mutex<HashMap<PathBuf, CachedFileHash>>>,
Without looking too deeply into this, I feel like this shouldn't be free to grow indefinitely, and should be a LRU cache of some sort.

2021-03-10 13:47 UTC, michaelwoerister commented
Good point -- I did not benchmark this on Windows.

2021-11-14 11:29 UTC, sylvestre commented
it needs to be rebased too :)
(hello Michael ;)

2021-12-01 09:24 UTC, michaelwoerister commented
Hi Sylvestre :)

I probably won't have time to work on this in the next couple of months. If anybody else is interested in this, feel free to take over.

2021-12-01 09:24 UTC, closed without merging