Update sccache-dist to use SCCACHE_LOG.
mozilla/sccache pull request #977
Opened 2021-03-20 23:44 UTC by rthomas

This fixes #969 which was overlooked when fixing #810.

2021-03-24 13:58 UTC, Xanewok approved these changes

2022-02-11 21:13 UTC, mitchhentges requested changes
Heh, I remember being affected by this last year. Thanks for the patch :+1: 
Would you mind updating the docs and tests that are referencing this?

2022-06-23 09:38 UTC, drahnr commented
Gentle ping :)

2022-06-24 19:35 UTC, rthomas commented
Sorry, had forgotten about this :) will look at it now.

2022-06-24 20:30 UTC, drahnr approved these changes

2022-06-24 20:31 UTC, merged